#!/usr/bin/env python

""" Initialize a new source file from a template.
"""
import optparse
import os
import shutil
import sys


ROOT = os.path.dirname(os.path.abspath(__file__))


def find_template(root, ext):
    items = os.listdir(root)
    for item in items:
        p, e = os.path.splitext(item)
        if e in [ext]:
            return item

def main():
    parser = optparse.OptionParser(usage='%prog [OPTIONS] newfile.ext')

    parser.add_option('-t',
                      '--template',
                      dest='template',
                      action='store',
                      type='string',
                      default='',
                      help='override template search with specified template')

    options, args = parser.parse_args()

    templates = os.path.join(ROOT, 'templates')

    for dst in args:
        base, ext = os.path.splitext(dst)
        if options.template:
            template = options.template
        else:
            template = find_template(templates, ext)

        if template:
            src = os.path.join(templates, template)
            if not os.path.exists(src):
                print(f'Template {src} does not exists.')
                continue

            if os.path.exists(dst):
                print(f'File {dst} already exists!')
                continue
            
            shutil.copy2(src, dst)


if __name__ == '__main__':
    main()
